[package]
name = "catr"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
rand = "0.8.5"

[dev-dependencies]
anyhow = "1.0.95"
pretty-print = "0.1.9"
pretty_assertions = "1.4.1"
